Repository juicity/juicity, pull requests merged in 2023-10, with the labels that each got.

#123 feat(cmd): enhance version print
  .github/workflows/seed-build.yml
  .github/workflows/seed-release-build.yml
  Makefile
  cmd/client/cgo_check.go
  cmd/client/cmd.go
  cmd/client/run.go
  cmd/internal/shared/version.go
  cmd/server/cgo_check.go
  cmd/server/cmd.go
  cmd/server/run.go
Labels: tested, feature

#130 Add docker CI
  .github/workflows/docker-publish.yml
Labels: ci, not-yet-tested

#132 ci(docker-publish): limit workflow triggers
  .github/workflows/docker-publish.yml
Labels: ci

#133 Fixed docker CI did not start when workflow update, add linux/arm64 Docker image
  .github/workflows/docker-publish.yml
Labels: ci, tested
