Repository juicity/juicity, pull requests merged in 2023-08, with the labels that each got.

#51 patch(server): add error handling for connClose
  pkg/log/log_test.go
  server/server.go
Labels: patch, not-yet-tested

#54 fix(server): support to dial domain in UDP (quic)
  go.mod
  go.sum
  internal/relay/udp.go
  server/server.go
Labels: fix, not-yet-tested

#53 feat(sever): log source origin metadata
  server/server.go
Labels: tested, feature

#52 ci: add linting workflow
  .github/workflows/lint.yml
  .golangci.yml
  cmd/client/run.go
  cmd/server/run.go
  internal/relay/tcp.go
  internal/relay/udp.go
  pkg/client/dialer/protect_linux.go
Labels: ci

#61 feat: support certificate pinning
  README.md
  cmd/client/README.md
  cmd/client/run.go
  cmd/server/README.md
  cmd/server/gen_certchain_hash.go
  common/utils.go
  config/config.go
Labels: tested, feature

#67 chore: upgrade softwind and quic(to 0.37.2)
  cmd/client/run.go
  go.mod
  go.sum
  internal/relay/relay.go
  internal/relay/tcp.go
  internal/relay/udp.go
  pkg/client/dialer/dialer.go
  pkg/client/dialer/protect_linux.go
  server/mixed_server.go
  server/server.go
Labels: chore

#64 docs(server): add UUID Generator section
  cmd/server/README.md
Labels: documentation

#57 feat(internal/relay): add support to inspect source for UDP traffic
  internal/relay/relay.go
  internal/relay/udp.go
  server/server.go
Labels: feature

#56 feat(log): add exra cmd-flags for file logger
  cmd/client/README.md
  cmd/client/run.go
  cmd/internal/shared/arguments.go
  cmd/server/README.md
  cmd/server/run.go
  common/consts/log.go
  common/consts/relay.go
  common/utils.go
  go.mod
  go.sum
  pkg/log/log.go
  pkg/log/log_test.go
Labels: feature

#70 chore: upgrade quic-go to v0.37.3
  go.mod
  go.sum
Labels: chore

#73 ci: add Dockerfile
  Dockerfile
Labels: ci

#75 ci/optimize: docker refinement
  .dockerignore
  CODEOWNERS
  Dockerfile
Labels: ci, tested, optimize

#74 feat(server): support cmd generate-sharelink
  cmd/client/run.go
  cmd/server/README.md
  cmd/server/gen_certchain_hash.go
  cmd/server/gen_link.go
Labels: tested, feature

#77 chore/refactor: rework issue_templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/proposal.yml
  .github/ISSUE_TEMPLATE/support-request.md
  .github/ISSUE_TEMPLATE/support-request.yml
Labels: chore, refactor

#79 chore(pr_template): update pr_template section headers
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#80 optimize(generate-sharelink): judge whether really need to pin
  cmd/server/README.md
  cmd/server/gen_link.go
Labels: tested, optimize

#83 docs: add protocol spec
  README.md
  docs/spec.md
Labels: documentation

#84 docs(spec): add English version specification
  docs/spec.md
  docs/spec_en.md
Labels: documentation

#85 docs: add lang switch for spec.md
  README.md
  docs/spec.md
  docs/spec_en.md
Labels: documentation

#93 fix: fail to trigger auth timeout in some cases
  server/server.go
Labels: tested, fix

#91 fix: panic: unaligned 64-bit atomic operation
  go.mod
  go.sum
Labels: fix

#86 feat: support port forwarding
  cmd/client/README.md
  cmd/client/run.go
  common/consts/consts.go
  config/config.go
  go.mod
  go.sum
  internal/relay/relay.go
  internal/relay/udp.go
  server/forwarder.go
  server/server.go
  server/udp_endpoint.go
Labels: tested, feature

#92 feat(server): support dial using socks5, http, vmess, vless...
  cmd/client/README.md
  cmd/server/README.md
  cmd/server/run.go
  cmd/server/server.go
  config/config.go
  go.mod
  go.sum
  server/server.go
Labels: tested, feature

#96 chore: bump quic-go to v0.37.5
  go.mod
  go.sum
Labels: chore

#100 chore: upgrade quic-go to v0.37.6
  go.mod
  go.sum
Labels: chore, tested

#101 chore: bump quic-go to v0.38.0
  cmd/client/README.md
  cmd/server/README.md
  go.mod
  go.sum
Labels: chore

#103 optimize: use raw udp conn to solve quic in quic problem
  cmd/server/README.md
  cmd/server/run.go
  config/config.go
  go.mod
  go.sum
  server/forwarder.go
  server/inflight.go
  server/server.go
  server/udp_endpoint.go
Labels: tested, optimize
