Repository juicity/juicity, pull requests merged in 2023-07, with the labels that each got.

#3 chore: add issue_templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support-request.md
Labels: chore

#2 chore: add pr_template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#1 chore: add codeowners
  CODEOWNERS
Labels: chore

#5 chore: add pre-commit-config
  .pre-commit-config.yaml
Labels: chore

#6 ci/chore: add friendly-filenames
  install/friendly-filenames.json
Labels: chore, ci

#7 ci: bootstrap workflows
  .github/workflows/build.yml
  .github/workflows/daily-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
Labels: ci

#8 ci(seed-build): general refinement
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
Labels: ci

#9 docs(readme): add repo badges
  README.md
Labels: chore

#10 docs(readme): add stargazers over time
  README.md
Labels: documentation

#11 ci/feat(seed-build): add darwin build
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
  go.mod
  go.sum
  install/friendly-filenames.json
Labels: ci, feature

#12 ci/feat(seed-build): add windows and android build
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
  install/friendly-filenames.json
Labels: ci, feature

#13 ci/fix(seed-build): windows suffix
  .github/workflows/seed-build.yml
Labels: ci, fix

#17 feat: support send_through
  cmd/server/README.md
  cmd/server/run.go
  config/config.go
  go.mod
  go.sum
  server/relay.go
  server/server.go
Labels: tested

#16 refactor/patch: rework logger instantiation
  cmd/client/run.go
  cmd/server/run.go
  internal/relay/relay.go
  internal/relay/tcp.go
  internal/relay/udp.go
  pkg/log/log.go
  pkg/log/log_test.go
  server/server.go
Labels: patch, refactor

#21 docs(readme): add daed client as a new juicity client
  README.md
Labels: documentation

#29 chore: add example-{client,server}.json
  .github/workflows/seed-build.yml
  .github/workflows/seed-release-build.yml
  install/example-client.json
  install/example-server.json
Labels: chore, tested

#25 docs: refine README
  .github/workflows/seed-release-build.yml
  cmd/client/README.md
  cmd/server/README.md
Labels: documentation

#26 chore/optimize(log): change log format to datetime
  cmd/client/run.go
  cmd/server/run.go
  install/juicity-client.service
  install/juicity-server.service
  internal/relay/relay.go
  pkg/log/log.go
  pkg/log/log_test.go
  server/server.go
Labels: chore, tested, optimize

#32 ci(build,pr-build,daily-build): enable check_run stages
  .github/workflows/build.yml
  .github/workflows/daily-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
  .github/workflows/seed-release-build.yml
Labels: ci, tested

#33 hotfix/ci(build): fix secret inputs missing issue
  .github/workflows/build.yml
  .github/workflows/daily-build.yml
Labels: ci, hotfix, not-yet-tested

#35 ci(build): demise post-actions stage for main-build
  .github/workflows/build.yml
  .github/workflows/daily-build.yml
Labels: ci, not-yet-tested

#37 ci: add generate-changelogs workflow
  .github/workflows/generate-changelogs.yml
  CHANGELOGS.md
Labels: ci

#36 optimize: little more faster
  cmd/server/run.go
  go.mod
  go.sum
  server/server.go
Labels: tested, optimize

#31 feat/refactor: add constant pkg
  common/consts/relay.go
  internal/relay/relay.go
  internal/relay/udp.go
Labels: tested, feature, refactor

#43 chore(pr_template): fix typos
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#46 docs: add authentication docs of http/socks5 listening
  cmd/client/README.md
Labels: documentation

#39 feat/refactor(pkg/log): add log writer stream
  cmd/client/README.md
  cmd/client/run.go
  cmd/server/README.md
  cmd/server/run.go
  go.mod
  go.sum
  pkg/log/log.go
  pkg/log/log_test.go
Labels: tested, feature, refactor
