Repository juicity/juicity, pull requests merged in 2025-02, with the labels that each got.

#177 ci: update checkout and setup-go to latest
  .github/workflows/docker-publish.yml
  .github/workflows/lint.yml
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
  .github/workflows/seed-release-build.yml
Labels: ci, tested

#176 chore: update outbound
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  Dockerfile
  cmd/client/run.go
  cmd/server/server.go
  go.mod
  go.sum
  internal/relay/relay.go
  internal/relay/tcp.go
  internal/relay/udp.go
  pkg/client/dialer/dialer.go
  pkg/client/dialer/protect_linux.go
  server/forwarder.go
  server/inflight.go
  server/mixed_server.go
  server/server.go
  server/udp_endpoint.go
Labels: chore

#178 ci: reset to use origin seed
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
  .github/workflows/seed-release-build.yml
Labels: ci, not-yet-tested
